### PR TITLE
Cleaning code and purging unnecessary

### PR DESCRIPTION
**Pull request by piokli**
Delete the unnecessary World.tscn and unused particle scenes/scripts. There are too many layers for such a project xd Maybe also take Player.tscn outside the Gamplay.tscn or/and give Gameplay "more stuff to do" like managing levels/player's and toast's position

### CODE REVIEW

**Comment by piokli** [comment]
I moved gameplay.cs stuff to player's script. This way it'll be easier to make and transition between levels

**Comment by jlatusek** [comment]
It looks fine, but there is a little problem with GitHub... 
You see, you used the debugging-and-particles branch, added changes, and created this branch. Unfortunately, I can't merge these changes separately(if I merge this PR, all changes from other PR will be added to the master). So there are two solutions. You can separate the 3 last commits of this change (I think that it is not possible because you change some code added in the debugging-and-particles branch, or we can wait to merge changes in other PR and work with that these changes. 

In the future, please mark that some PR is related to changes from other PR. In example "related to #5" :))

**Comment by jlatusek** [comment]
Or better mark it as "merge after #5"
By marking, I mean writing comment with this text :))

**Review by jlatusek — APPROVED** [review]
LGTM

**Pull request merged**
