### PR TITLE
Cu-2t42pb9 Implement stop button 

### PR DESCRIPTION
**Pull request by jlatusek**
I want to stop the butter from moving if any other button isn't clicked - except for the down arrow initiating this action.

### CODE REVIEW

**Comment by jlatusek** [comment]
Task linked: [CU-2t42pb9 mv_down zwalnia masełko (jeżeli żaden inny klawisz nie wciśnięty może)](https://app.clickup.com/t/2t42pb9)

**Comment by piokli** [comment]
Our Butter stopping immidiately seems a little bit too stiff imo. Maybe it could use a little bit of Lerp() like in Player.Idle()? Or maybe this will look good enough when Player animations come in. WDYT?

**Comment by jlatusek** [comment]
> Our Butter stopping immediately seems a little bit too stiff imo. Maybe it could use a little bit of Lerp() like in Player.Idle()? Or maybe this will look good enough when Player animations come in. WDYT?

Hmm, maybe if we add some animation to our game, it will look better? Now I've tried larp with weight set to 0.2f, and it still seems to be a more like stop than smooth stop. Maybe we should set a little less weight in Idle mod instead and level it here to 0.1? What do you think about it?

**Review by piokli — APPROVED** [review]
looks good! but.... What do you think about lowering Payer's max_speed to "punish" for using "mv_down" to much? Because someone could just press "down" the whole time and it would only be a benefit (and he would ask why didn't we make butter slow by default (i.e. 0.2f Lerp)... I think, if we make butter accelerate less and/or cut ouff max_speed when holding "mv_down" it would make more sense (kind of the same as crouching). what do you think?

**Comment by jlatusek** [comment]
I've added limitations to maximum speed and maximum acceleration during crouching :))

**Review by piokli — APPROVED** [review]
Nice! exactly what I had in mind - it seems it needs no tweaking  :)

**Pull request merged**
